### PR TITLE
feat: Added GoSquared Analytics

### PR DESCRIPTION
**Pull request by soulgalore**

### CODE REVIEW

**Comment by patrickhulce** [comment]
Ya know you can please feel free to add more than one at a time I don't have a problem with larger PRs :)

**Comment by patrickhulce** [comment]
(doing one at a time means we gotta fix the merge conflicts after each one)

**Comment by soulgalore** [comment]
Ok, the next time I'll do a batch!

**Comment by soulgalore** [comment]
Also if you could publish to npm the next time you feel you merged the most that would be great!

**Comment by patrickhulce** [comment]
> Also if you could publish to npm the next time you feel you merged the most that would be great!

Definitely I'll do that as soon as I merge these :)

**Comment by patrickhulce** [comment]
@soulgalore just published 0.2.0 🎉

**Pull request merged**
