### PR TITLE
feat(entities): update entities for Yahoo! JAPAN Ads

### PR DESCRIPTION
**Pull request by shigeki**
As request by @sisidovski, we, Yahoo! JAPAN, checked our entities. 
This fix reflects the current use of our ad scripts. Please update it.

### CODE REVIEW

**Review by patrickhulce — APPROVED** [review]
thanks @shigeki!

**Comment by shigeki** [comment]
@patrickhulce Thanks but CI was failed.  I'm not sure how the test is working.  Is the following diff OK?

```diff
diff --git a/lib/__snapshots__/index.test.js.snap b/lib/__snapshots__/index.test.js.snap
index 5ba4b4e..4ae3c19 100644
--- a/lib/__snapshots__/index.test.js.snap
+++ b/lib/__snapshots__/index.test.js.snap
@@ -295,7 +295,7 @@ Array [
   "Instagram - https://www.instagram.com/zurikenya/",
   "Google Analytics - https://google-analytics.com/urchin.js",
   "Criteo - https://sslwidget.criteo.com/pvx/display.js",
-  "undefined - https://b92.yahoo.co.jp/search/",
+  "Yahoo! JAPAN - b92.yahoo.co.jp/js/s_retargeting.js",
   "FontAwesome CDN - https://kit.fontawesome.com/yourcode.js",
   "Yandex APIs - https://api-maps.yandex.ru/undefined/",
   "Hubspot - https://forms.hubspot.com/outpost/lead-flows-js/error.gif",
```

**Comment by patrickhulce** [comment]
Yep even better! 👍

**Comment by shigeki** [comment]
Thanks. The snapshot file was fixed in 35fe5206ad0de916d753cddfaf57f468ec30ec3e.

**Comment by shigeki** [comment]
CI is all happy. Thanks.

**Comment by sisidovski** [comment]
Thanks @shigeki for the correction, and @patrickhulce as always!

**Pull request merged**
