### PR TITLE
Add homepage to Mouseflow

### PR DESCRIPTION
**Pull request by lasseschou**

### CODE REVIEW

**Review by patrickhulce — APPROVED** [review]
thanks! 🎉

**Comment by lasseschou** [comment]
@patrickhulce do you still maintain the data, or you do need help?

**Comment by patrickhulce** [comment]
@lasseschou I do but at an infrequent rate. Help always appreciated!

There is a script to query latest data and instructions for contributions if you want to help out:)

**Comment by lasseschou** [comment]
Great stuff. Yup, I've seen the SQL queries and instructions. So does this mean that you're doing that locally, now and then, and then upload the results? Would it be an idea to set up a monthly job to automatically query the dataset and deploy a new version? Only thing is, it's not totally free - but since Google is using the dataset in Lighthouse, I guess maybe @paulirish can help with this?

**Comment by patrickhulce** [comment]
> does this mean that you're doing that locally, now and then, and then upload the results?

Exactly.

> Would it be an idea to set up a monthly job to automatically query the dataset and deploy a new version? Only thing is, it's not totally free

Yeah cost is what was stopped me.

I'm not sure that Lighthouse is using anything other than the classifications at the moment (which wouldn't be helped by automated queries), but I certainly wouldn't turn down funding for it from @paulirish if it's there ;)

**Comment by lasseschou** [comment]
Even the classifications that Lighthouse use need regular updates. It looks like it's still using data from 4+ years ago, and new third-party entities pop up all the time. 

Commenting on a pull request like this probably isn't the best way, but @paulirish if you could pull some strings and get @patrickhulce a GCP account for third-party-web with a generous free tier for querying the HTTP Archive, I'm sure we could get an automated monthly job up and running, which would benefit Lighthouse (get more up-to-date third-party entities), but also help raise awareness of how CPU heavy the third-parties are, and thus apply a pressure to reduce the third-party load generally.

**Pull request merged**
