### PR TITLE
Adds Segmanta to entities

### PR DESCRIPTION
**Pull request by benschwarz**

### CODE REVIEW

**Comment by AfrouzHojati** [comment]
Hi patrickhulce,

I have noticed that the third party categorization in [this project](https://github.com/WPO-Foundation/webpagetest) is different. It might be useful for you.

But I don't know how to find their data ( a dataset including third parties and category assigned to them) in order to compare it with yours . can your help me with that? 

Thanks

**Comment by patrickhulce** [comment]
Thanks @AfrouzHojati but what third-party categorization are you talking about in WebPageTest? I'm quite familiar with the tool but I'm not aware it does any sort of hierarchical classification of third-party entities like this project. Do you have a screenshot of the part of the UI you're referring to for third-party categorization I can take a look at?

If you're referring to the classification in the "Request Map" link of every test results that is a separate project that also happens to use this dataset here.

**Comment by AfrouzHojati** [comment]
Thank you for your answe @patrickhulce. yes, I am referring to the classification in the "Request Map".

So, would you tell me what is the basis of your classification? how did you classified third parties? Did you check them manually?

**Comment by patrickhulce** [comment]
> Did you check them manually?

Yep. A human contributor at one point was responsible for looking at the entity and deciding what category it fell into.

**Pull request merged**
